version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
  backend:
    build:
      context: ./backend
    environment:
      SERVER_PORT: 8000
      PG_HOST: db
      PG_USER: your_username
      PG_PASSWORD: your_password
    ports:
      - "8000:8000"
    depends_on:
      - "db"
